version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/test
    volumes:
      - .:/app
    command: ["npm", "start"]

  mongo:
    image: mongo
    container_name: smas-nan
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: